### PR TITLE
Adapt mobile app code to Ionic 5

### LINKED ISSUE #242: Support Ionic 5
See https://docs.moodle.org/dev/Adapt_your_Mobile_plugins_to_Ionic_5

### PR DESCRIPTION
**Pull request by dpalou**
Hi, this PR is to adapt the mobile app code to Ionic 5. I wasn't able to test this code because I don't have an API key and I don't have enough time to configure this properly, it would be great if you could verify that it works as expected. The template has barely changed so it I think it should work fine.

Fixes #242

### CODE REVIEW

**Comment by dpalou** [comment]
Someone with permissions should link this PR to the issue: https://github.com/ncstate-delta/moodle-mod_zoom/issues/242

**Comment by smbader** [comment]
Hey Dani,

Thanks for working on this. I'll work on testing this in our test environment.

**Comment by smbader** [comment]
I've tested this the best way I know how.  Everything looks to be working well.

**Review by smbader — APPROVED** [review]

**Comment by smbader** [comment]
Thank you @dpalou!

**Pull request merged**
