### PR TITLE
issue #557: Add SVG and PNG icon for calendar

### LINKED ISSUE #557: Unit test test_svg_fallback failing in Moodle 4.3
The unit test has originated from the tracker https://tracker.moodle.org/browse/MDL-67271. In the dev update (https://moodledev.io/docs/4.3/devupdate#icons) it mentions this.

> Third-party plugins are strongly encouraged to follow suit, adding missing SVG files too, to avoid PHPUnit test failures.
> 
> The SVG icons in Moodle LMS were sourced from https://fontawesome.com/search?m=free&o=r, which offers free icons under the Creative Commons Attribution 4.0 International license, consistent with the Moodle icon set.

Resulting in this issue. The font awesome mapping in https://github.com/ncstate-delta/moodle-mod_zoom/blob/main/lib.php#L989-L998 requires the icon for calendar to be added to the plugin.

<details>
  <summary>PHPUnit test run of the test_svg_fallback on Moodle 4.3.2 (Build: 20231222)</summary>

  ```
  root@c3e2c38a9c70:/var/www/vanilla-403# vendor/bin/phpunit --filter test_svg_fallback
  Moodle 4.3.2 (Build: 20231222), 6a6043c47b80ea6f64f69d8a41487ded3444a970
  Php: 8.1.24, pgsql: 14.0 (Debian 14.0-1.pgdg110+1), OS: Linux 6.4.12-060412-generic x86_64
  PHPUnit 9.5.28 by Sebastian Bergmann and contributors.

  ...............................................................  63 / 507 ( 12%)
  ............................................................... 126 / 507 ( 24%)
  ............................................................... 189 / 507 ( 37%)
  ............................................................... 252 / 507 ( 49%)
  ............................................................... 315 / 507 ( 62%)
  ............................................................... 378 / 507 ( 74%)
  ............................................................... 441 / 507 ( 86%)
  .............F................................................. 504 / 507 ( 99%)
  ...                                                             507 / 507 (100%)

  Time: 00:12.384, Memory: 344.00 MB

  There was 1 failure:

  1) core\output\icon_system_fontawesome_test::test_svg_fallback with data set #454 ('mod_zoom:i/calendar', '/var/www/vanilla-403/mod/zoom', 'i/calendar')
  No SVG equivalent found for 'mod_zoom:i/calendar'
  Failed asserting that false is true.

  /var/www/vanilla-403/lib/tests/output/icon_system_fontawesome_test.php:64
  /var/www/vanilla-403/lib/phpunit/classes/advanced_testcase.php:81

  FAILURES!
  Tests: 507, Assertions: 507, Failures: 1.
  ```
</details>

### PR DESCRIPTION
**Pull request by ScottVerbeek**
Resolves issue #557 fixing unit test test_svg_fallback on Moodle 4.3.

```
root@c3e2c38a9c70:/var/www/vanilla-403# vendor/bin/phpunit --filter test_svg_fallback 
Moodle 4.3.2 (Build: 20231222), 6a6043c47b80ea6f64f69d8a41487ded3444a970
Php: 8.1.24, pgsql: 14.0 (Debian 14.0-1.pgdg110+1), OS: Linux 6.4.12-060412-generic x86_64
PHPUnit 9.5.28 by Sebastian Bergmann and contributors.

...............................................................  63 / 507 ( 12%)
............................................................... 126 / 507 ( 24%)
............................................................... 189 / 507 ( 37%)
............................................................... 252 / 507 ( 49%)
............................................................... 315 / 507 ( 62%)
............................................................... 378 / 507 ( 74%)
............................................................... 441 / 507 ( 86%)
............................................................... 504 / 507 ( 99%)
...                                                             507 / 507 (100%)

Time: 00:11.212, Memory: 344.00 MB

OK (507 tests, 507 assertions)
```

 Fixes #557

### CODE REVIEW

**Comment by jrchamp** [comment]
Thanks @ScottVerbeek! We'll do some testing on our side and plan to merge this in the next release.

**Comment by jrchamp** [comment]
Hi @ScottVerbeek, I wasn't able to push directly to your branch, so I opened https://github.com/catalyst/moodle-mod_zoom/pull/1 to optimize the SVG files. With that change added on, I'd be happy to approve and merge this tomorrow.

**Review by smbader — APPROVED** [review]
Great catch, thank you for the PR.

**Comment by smbader** [comment]
@jrchamp will add SVGOMG optimizations in a separate pull request.

**Pull request merged**
